apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keel
  namespace: kube-system
spec:
  repo: https://charts.anitya.net/keel
  chart: keel
  targetNamespace: kube-system
  version: v1.0.5
